//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exam1.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActsOfBuying
    {
        public int IdActB { get; set; }
        public Nullable<int> IdAccount { get; set; }
        public Nullable<int> IdPhone { get; set; }
    
        public virtual Accounts Accounts { get; set; }
        public virtual Phones Phones { get; set; }
    }
}
